matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.6
      services: xvfb

    - os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: generic
      services: xvfb

cache: pip
branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change

install:
  # check python version
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 --version; fi
  
  # install pandoc
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install pandoc; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install pandoc; fi

  # get pipenv to install dependencies
  - pip3 install pipenv

  # run through install as written in docs (but already in env)
  # except no wxPython compiled for linux on pypi, and building from source takes ~45 min
  # so instead grab build from online
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pipenv run pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython; fi

  - pipenv install --dev --skip-lock
  - pipenv run pip install git+https://github.com/labjack/LabJackPython.git

  # install ffmpeg
  # install avbin
  
  # for easier debugging
  - pip list


# setup virtual frame buffer (i.e. headless display)
before_script:
  - export DISPLAY=:99.0
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start

script:
  # run tests
  - pipenv run py.test tests --cov pyStim
  # make rst copy of readme for docs
  - pandoc --from=markdown --to=rst --output=docs/source/README.rst README.md
  # build documentation
  - cd docs
  # pipenv run sphinx-build -W -b html source build/html  # warnings as errors
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pipenv run sphinx-build -W -b html source build/html; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pipenv run sphinx-build -b html source build/html; fi  # b/c matplot python framework runtime warning

after_success:
  # push coverage results
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pipenv run coveralls; fi

deploy:
  # edge:
  #   branch: v1.8.47  # temp since deploy broken on latest
  # push html documentation to github pages
  provider: pages
  skip_cleanup: true
  github_token: $travis_sphinx_ghpages
  local_dir: docs/build/html
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == 'linux'
